### ISSUE TITLE
Variable Assignment issues in 5.4

### ISSUE THREAD

**Issue by bpsut** [danStich/worst-r#1]
First, thanks for the book/resource. This is great for someone coming from Python and needing to use R for a project.

I noticed in Chapter/Section 5.4 you have a couple instances where you create distributions to plot (samp1, samp2, samp3), but then actually plot **samp**, samp2, samp3. This makes your plots, especially the Beta distribution, incorrect.

Beta distribution plot in the book:
![BetaInBook](https://github.com/user-attachments/assets/a2c58322-7b5c-4598-b27e-7636f0b4a7c1)
Correct Beta distribution plot:
![CorrectBetaPlot](https://github.com/user-attachments/assets/4959c8d3-51bc-4d09-9c08-35e6e4d14dee)

**Comment by danStich** [comment]
Hi Brad, Thanks so much for pointing this out, and even more so for opening an issue so I can track it. It's also really nice to hear that this is a useful resource for folks!!

I have a pile of typos and other points of clarification on my whiteboard from the past two semesters teaching the course here that I am hoping to implement as well. Hoping to also update some of the examples with some new datasets before the next time I teach the class in spring 26.

**Comment by bpsut** [comment]
Yeah, it took a minute to find the actual GitHub repo, I expected it to be easier to submit issues on a GitHub book. This is a great resource for me since I'm refreshing my stats knowledge and learning R at the same time. It has also prompted me to find similar stats summary tools for Python (hello statsmodels!). I've blasted through the first 10 chapters in 2 days, but I'm happy to open issues as I find more (like the top of 9.7 I think should have a plot).

**Comment by danStich** [comment]
Fixed beta dist samples and missing figure in 9.7

**Comment by danStich** [comment]
Hi Brad,

I just fixed these two things. Please feel free to submit other issues as you run across them. I'll try to add my checklist of typos from the office whiteboard in some kind of overarching issue as well that folks can check ahead of time. I'll probably also add a contributing.md file for info about opening issues or making pull requests. I just got versed in doing so for an R package paper that is in review. I'll also think about trying to make the GitHub link/issue invite clearer in the textbook itself and provide some additional details in the readme.md.

I never envisioned some years ago that the book might actually be used outside of our class. But now that folks are finding and using it, should probably add some clarification 🙂.

Thanks again for pointing these out.

Dan

----
Daniel S. Stich (he/him)
Associate Professor, Biology Department and
Secretary-Treasurer, NY Chapter American Fisheries Society
113A Perna Science, SUNY Oneonta, NY 13820
Office: 607-436-3734
Cell: 518-860-4107
Email: ***@***.***
Website: danstich.github.io/stich<https://danstich.github.io/stich/index.html>
________________________________
